### ISSUE TITLE
Eray Chumak

### ISSUE THREAD

**Issue by b-user** [esskayesss/kanagawa-qbtheme#3]
Hello.
The first lines of your .qss file say "qBittorrent / Black Theme @author Eray Chumak".
Could you please mention Eray Chumak in README.md?

**Comment by esskayesss** [comment]
only if they request it.

i don't get why people want their names attached to these theme files anyway-- as if its some top secret original content or a secret algorithm. The docs for exist on the web. i've made other themes and never included my name in any of the files.

the only reason i let those lines be there is because qbittorrent black is another theme i really enjoy and have used for a long time. this was my way to advertise it without being weird. 

i don't think the actual authors care so much about these things.

**Comment by b-user** [comment]
I downloaded three themes with different names from different authors.
I started to understand the structure of themes and it turned out that this is one theme, not three.

If I had seen the author of the original thread, it would have saved me time.

**Comment by esskayesss** [comment]
im sorry i didn't quite understand your case, and it seems i had misgauged your intent initially. 

that said, if you're developing a theme, you're free to pick this repo and change the color values to suit your own theme. thats how a lot of themes are ported and it would be totally fine by me. you're free to use the files in this repo without giving me credit for the template and format of files.
